### ISSUE TITLE
YOU CANNOT INCLUDE CESIUM!!!

### ISSUE THREAD

**Issue by jcgter777** [164-dame/Konstrukt#6]
Your program was rejected from the Cemetech archives because you have Cesium in there w/o permission, and unsigned apps can't be loaded onto a calc. 

I would recommend you completely not include anything about Cesium.

**Comment by SanjivanM** [comment]
I second that, also, your readme _/explicitly/_ says that Cesium isn't needed, and there is no need to include it anyways.  There is no advantage to running a BASIC program in a shell (except for the ability to run from the Archive, although that's a feature of CE OS 5.3)

**Comment by 164-dame** [comment]
Noted, I will remove it and resubmit. There purpose of cesium was to run games, and worked in older versions when cesium was still a program and not an app. I'll push the update soon. 😉
